close all;
clc;
clear;
fs=5000;
t=0:1/fs:1.0-1/fs;
%N=1.0*fs;
N=length(t);
%Am=0.8;
Am=2.0;
s=Am*sin(2*pi*50*t);
%A=1;
A=0.5;
noi=A*randn(1,N);
d=s+noi;
SNR=10*log10(Am*Am);
figure;
subplot(311);
plot(s);
title('原信号');
subplot(312);
plot(noi);
title('噪声');
subplot(313);
plot(d);
title('加噪信号');
%%
nsamp=500;
overlap=50;
nfft=1024;
nlag=100;
%%
figure;
subplot(221);
bspec1=bispeci(noi,nlag,nsamp,overlap,'unbiased',nfft,0);
title('bispectrum of noi');
subplot(222);
[bspec2,waxis2]=bispeci(d,nlag,nsamp,overlap,'unbiased',nfft,0);
title('bispectrum of d');
subplot(223);
mesh(abs(bspec1));
title('noi');
subplot(224);
mesh(abs(bspec2));
title('d');
%%
figure;
subplot(221);
bspec3=bispecd(noi,nfft,7,nsamp,overlap);
title('bispectrum of noi');
subplot(222);
[bspec4,waxis4]=bispecd(d,nfft,7,nsamp,overlap);
title('bispectrum of d');
subplot(223);
mesh(abs(bspec3));
title('noi');
subplot(224);
mesh(abs(bspec4));
title('d');